create table if not exists public.google_calendar_channels (
  id uuid primary key, -- channel ID (generated by client or DB)
  user_id uuid references auth.users on delete cascade not null,
  resource_id text, -- Google's resource ID for the watch
  expiration timestamp with time zone,
  sync_token text, -- Google's syncToken for incremental event list queries
  created_at timestamp with time zone default now()
);

alter table public.google_calendar_channels enable row level security;

create policy "Users can manage their own calendar watch channels"
  on public.google_calendar_channels
  for all
  using (auth.uid() = user_id);
